// Package classify sorts changed files into classes (source, test, docs,
// generated, binary, meta) using in-file markers, path conventions and
// well-known filenames, so a report can separate churn in generated and
// vendored bulk from the hand-written code a reviewer must actually
// read. It also measures minification signals (line lengths, sourcemap
// presence) for JS files.
//
// A class is a reading-order aid, never a trust level: markers and paths
// are attacker-writable, so a "generated" label must not lower security
// scrutiny. Every non-default result carries the evidence that produced
// it, letting the consumer judge the claim.
package classify

import (
	"bytes"
	"fmt"
	"slices"
	"strings"
)

type Class string

const (
	Source    Class = "source"
	Test      Class = "test"
	Docs      Class = "docs"
	Generated Class = "generated"
	Binary    Class = "binary"
	Meta      Class = "meta"
)

type Result struct {
	Class    Class
	Evidence string
}

// generatedMarkers are matched case-insensitively against the head of the
// file. The Go convention, Meta's @generated, and amalgamation banners
// cover the vast majority of real generated files.
var generatedMarkers = []string{
	"do not edit",
	"@generated",
	"amalgamation of many separate",
	"automatically generated",
	"autogenerated",
	"generated by",
}

var generatedPathParts = []string{"dist", "vendor", "node_modules", "__generated__"}

var generatedSuffixes = []string{
	".min.js", ".min.mjs", ".min.cjs", ".min.css",
	".map", ".tsbuildinfo",
	".pb.go", "_pb2.py", ".pb.cc", ".pb.h",
}

var testPathParts = []string{"test", "tests", "__tests__", "testdata", "spec", "fixtures"}

var docsSuffixes = []string{".md", ".markdown", ".rst", ".adoc"}

var docsBasenames = []string{"license", "licence", "notice", "authors", "changelog", "readme", "copying"}

var metaBasenames = []string{
	"package.json", "package-lock.json", "go.mod", "go.sum",
	"cargo.toml", "cargo.toml.orig", "cargo.lock", ".cargo_vcs_info.json",
	"tsconfig.json", "makefile",
}

// File classifies a tree-relative path. head is the first few KB of
// content (from whichever version has the file); binary comes from the diff.
func File(relPath string, head []byte, binary bool) Result {
	if binary {
		return Result{Binary, "binary content"}
	}
	lower := strings.ToLower(relPath)
	base := lower[strings.LastIndex(lower, "/")+1:]
	segs := strings.Split(lower, "/")
	dirSegs := segs[:len(segs)-1]

	if m := markerIn(head); m != "" {
		return Result{Generated, fmt.Sprintf("marker in file head: %q", m)}
	}
	for _, s := range generatedSuffixes {
		if strings.HasSuffix(base, s) {
			return Result{Generated, "path rule: *" + s}
		}
	}
	for _, seg := range dirSegs {
		for _, g := range generatedPathParts {
			if seg == g {
				return Result{Generated, "path rule: " + g + "/"}
			}
		}
	}
	for _, seg := range dirSegs {
		for _, t := range testPathParts {
			if seg == t {
				return Result{Test, "path rule: " + t + "/"}
			}
		}
	}
	if strings.HasSuffix(base, "_test.go") || strings.Contains(base, ".test.") || strings.Contains(base, ".spec.") {
		return Result{Test, "test filename"}
	}
	for _, s := range docsSuffixes {
		if strings.HasSuffix(base, s) {
			return Result{Docs, "doc filename"}
		}
	}
	for _, d := range docsBasenames {
		if base == d || strings.HasPrefix(base, d+".") {
			return Result{Docs, "doc filename"}
		}
	}
	if len(dirSegs) > 0 && dirSegs[0] == "docs" {
		return Result{Docs, "path rule: docs/"}
	}
	if slices.Contains(metaBasenames, base) {
		return Result{Meta, "manifest/metadata filename"}
	}
	if strings.HasPrefix(base, ".") || (len(segs) > 1 && strings.HasPrefix(segs[0], ".")) {
		return Result{Meta, "dotfile"}
	}
	return Result{Source, ""}
}

func markerIn(head []byte) string {
	if len(head) == 0 {
		return ""
	}
	h := bytes.ToLower(head)
	if i := slices.IndexFunc(generatedMarkers, func(m string) bool {
		return bytes.Contains(h, []byte(m))
	}); i >= 0 {
		return generatedMarkers[i]
	}
	return ""
}

// JSMetrics are minification measurements, reported rather than judged.
type JSMetrics struct {
	MaxLine   int  `json:"maxLine"`
	AvgLine   int  `json:"avgLine"`
	Lines     int  `json:"lines"`
	SourceMap bool `json:"sourceMap"`
}

func Metrics(content []byte) JSMetrics {
	m := JSMetrics{SourceMap: bytes.Contains(content, []byte("sourceMappingURL"))}
	for line := range bytes.Lines(content) {
		line = bytes.TrimSuffix(line, []byte("\n"))
		m.Lines++
		if len(line) > m.MaxLine {
			m.MaxLine = len(line)
		}
		m.AvgLine += len(line)
	}
	if m.Lines > 0 {
		m.AvgLine /= m.Lines
	}
	return m
}
