package classify

import (
	"bytes"
	"testing"
)

func TestFile(t *testing.T) {
	amalgamation := []byte("#ifndef X\n/*\n** This file is an amalgamation of many separate C source files from SQLite\n*/")
	goGen := []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x")

	cases := []struct {
		path   string
		head   []byte
		binary bool
		want   Class
	}{
		{"sqlite3-binding.c", amalgamation, false, Generated},
		{"x.pb.go", goGen, false, Generated},
		{"plain.go", goGen, false, Generated}, // marker beats extension
		{"dist/index.js", nil, false, Generated},
		{"lib/foo.min.js", nil, false, Generated},
		{"dist/x.tsbuildinfo", nil, false, Generated},
		{"test/foo.js", nil, false, Test},
		{"src/foo.test.js", nil, false, Test},
		{"callback_test.go", nil, false, Test},
		{"README.md", nil, false, Docs},
		{"LICENSE", nil, false, Docs},
		{"package.json", nil, false, Meta},
		{".github/workflows/ci.yml", nil, false, Meta},
		{"blob.wasm", nil, true, Binary},
		{"lib/command.js", []byte("'use strict';\nconst x = 1;"), false, Source},
		{"sqlite3.go", []byte("package sqlite3"), false, Source},
	}
	for _, c := range cases {
		got := File(c.path, c.head, c.binary)
		if got.Class != c.want {
			t.Errorf("File(%q) = %s (%s), want %s", c.path, got.Class, got.Evidence, c.want)
		}
		if got.Class == Generated && got.Evidence == "" {
			t.Errorf("File(%q): generated without evidence", c.path)
		}
	}
}

func TestMetrics(t *testing.T) {
	minified := append(bytes.Repeat([]byte("x"), 4000), []byte("\n//# sourceMappingURL=x.map\n")...)
	m := Metrics(minified)
	if m.MaxLine != 4000 || !m.SourceMap {
		t.Errorf("Metrics = %+v", m)
	}

	normal := []byte("const a = 1;\nconst b = 2;\n")
	m = Metrics(normal)
	if m.MaxLine >= 100 || m.SourceMap {
		t.Errorf("Metrics(normal) = %+v", m)
	}
}
