// Package classify sorts changed files into classes (source, test, docs,
// generated, binary, meta) using in-file markers, path conventions and
// well-known filenames, so a report can separate churn in generated and
// vendored bulk from the hand-written code a reviewer must actually
// read. It also measures minification signals (line lengths, sourcemap
// presence) for JS files.
//
// A class is a reading-order aid, never a trust level: markers and paths
// are attacker-writable, so a "generated" label must not lower security
// scrutiny. Every non-default result carries the evidence that produced
// it, letting the consumer judge the claim.
package classify

import (
	"bytes"
	"fmt"
	"regexp"
	"slices"
	"strings"
)

type Class string

const (
	Source    Class = "source"
	Test      Class = "test"
	Docs      Class = "docs"
	Generated Class = "generated"
	Binary    Class = "binary"
	Meta      Class = "meta"
)

// Basis records how strong a generated classification is: a marker or a
// generated-file suffix is confident; a path rule (dist/, vendor/) is
// weak, since such a file may be hand-edited (or a hidden payload). Only
// strong bases justify excluding a file from the review-surface subtotal.
type BasisKind string

const (
	BasisNone   BasisKind = ""
	BasisMarker BasisKind = "marker"
	BasisSuffix BasisKind = "suffix"
	BasisPath   BasisKind = "path"
)

func (b BasisKind) Strong() bool { return b == BasisMarker || b == BasisSuffix }

type Result struct {
	Class    Class
	Evidence string
	Basis    BasisKind
}

// generatedMarkers are matched case-insensitively against the head of the
// file. The Go convention, Meta's @generated, and amalgamation banners
// cover the vast majority of real generated files.
var generatedMarkers = []string{
	"do not edit",
	"@generated",
	"amalgamation of many separate",
	"automatically generated",
	"autogenerated",
	"generated by",
}

var generatedPathParts = []string{"dist", "vendor", "node_modules", "__generated__"}

var generatedSuffixes = []string{
	".min.js", ".min.mjs", ".min.cjs", ".min.css",
	".map", ".tsbuildinfo",
	".pb.go", "_pb2.py", ".pb.cc", ".pb.h",
}

var testPathParts = []string{"test", "tests", "__tests__", "testdata", "spec", "fixtures"}

var docsSuffixes = []string{".md", ".markdown", ".rst", ".adoc"}

var docsBasenames = []string{"license", "licence", "notice", "authors", "changelog", "readme", "copying"}

var metaBasenames = []string{
	"package.json", "package-lock.json", "go.mod", "go.sum", "version.json",
	"cargo.toml", "cargo.toml.orig", "cargo.lock", ".cargo_vcs_info.json",
	"tsconfig.json", "makefile",
}

// File classifies a tree-relative path. head is the first few KB of
// content (from whichever version has the file); binary comes from the diff.
func File(relPath string, head []byte, binary bool) Result {
	if binary {
		return Result{Class: Binary, Evidence: "binary content"}
	}
	lower := strings.ToLower(relPath)
	base := lower[strings.LastIndex(lower, "/")+1:]
	segs := strings.Split(lower, "/")
	dirSegs := segs[:len(segs)-1]

	if m := markerIn(head); m != "" {
		return Result{Class: Generated, Evidence: fmt.Sprintf("marker in file head: %q", m), Basis: BasisMarker}
	}
	for _, s := range generatedSuffixes {
		if strings.HasSuffix(base, s) {
			return Result{Class: Generated, Evidence: "path rule: *" + s, Basis: BasisSuffix}
		}
	}
	for _, seg := range dirSegs {
		for _, g := range generatedPathParts {
			if seg == g {
				return Result{Class: Generated, Evidence: "path rule: " + g + "/", Basis: BasisPath}
			}
		}
	}
	for _, seg := range dirSegs {
		for _, t := range testPathParts {
			if seg == t {
				return Result{Class: Test, Evidence: "path rule: " + t + "/"}
			}
		}
	}
	if strings.HasSuffix(base, "_test.go") || strings.Contains(base, ".test.") || strings.Contains(base, ".spec.") {
		return Result{Class: Test, Evidence: "test filename"}
	}
	for _, s := range docsSuffixes {
		if strings.HasSuffix(base, s) {
			return Result{Class: Docs, Evidence: "doc filename"}
		}
	}
	for _, d := range docsBasenames {
		if base == d || strings.HasPrefix(base, d+".") {
			return Result{Class: Docs, Evidence: "doc filename"}
		}
	}
	if len(dirSegs) > 0 && dirSegs[0] == "docs" {
		return Result{Class: Docs, Evidence: "path rule: docs/"}
	}
	if slices.Contains(metaBasenames, base) {
		return Result{Class: Meta, Evidence: "manifest/metadata filename"}
	}
	if strings.HasPrefix(base, ".") || (len(segs) > 1 && strings.HasPrefix(segs[0], ".")) {
		return Result{Class: Meta, Evidence: "dotfile"}
	}
	return Result{Class: Source}
}

func markerIn(head []byte) string {
	if len(head) == 0 {
		return ""
	}
	h := bytes.ToLower(head)
	if i := slices.IndexFunc(generatedMarkers, func(m string) bool {
		return bytes.Contains(h, []byte(m))
	}); i >= 0 {
		return generatedMarkers[i]
	}
	return ""
}

// embeddedMarkers recognize identity strings a file embeds about the
// UPSTREAM code it vendors (not the package's own version). A changed
// value is surfaced as a lead: "this blob embeds X, X moved A->B" points
// the agent at the real upstream change, which the vendoring package's
// changelog routinely under-describes.
//
// A small best-effort allowlist, not a general version detector. Adding a
// pattern is welcome: anchor and quote-delimit it so it cannot match
// ordinary code, and never match a package's OWN version (a top-level
// const Version, package.json "version"), which is tautological. Group 1
// is the marker name, group 2 its value.
var embeddedMarkers = []*regexp.Regexp{
	// C identity macros (#define <NAME>_VERSION / _SOURCE_ID "..."),
	// common in vendored C amalgamations shipped to avoid a system dep.
	regexp.MustCompile(`(?m)^#\s*define\s+(\w*(?:VERSION|SOURCE_ID))\s+"([^"]*)"`),
}

// EmbeddedMarkers extracts recognized upstream-identity markers from a
// vendored blob, keyed by marker name.
func EmbeddedMarkers(content []byte) map[string]string {
	out := map[string]string{}
	for _, re := range embeddedMarkers {
		for _, m := range re.FindAllSubmatch(content, -1) {
			out[string(m[1])] = string(m[2])
		}
	}
	return out
}

// JSMetrics are minification measurements, reported rather than judged.
type JSMetrics struct {
	MaxLine   int  `json:"maxLine"`
	AvgLine   int  `json:"avgLine"`
	Lines     int  `json:"lines"`
	SourceMap bool `json:"sourceMap"`
}

func Metrics(content []byte) JSMetrics {
	m := JSMetrics{SourceMap: bytes.Contains(content, []byte("sourceMappingURL"))}
	for line := range bytes.Lines(content) {
		line = bytes.TrimSuffix(line, []byte("\n"))
		m.Lines++
		if len(line) > m.MaxLine {
			m.MaxLine = len(line)
		}
		m.AvgLine += len(line)
	}
	if m.Lines > 0 {
		m.AvgLine /= m.Lines
	}
	return m
}
