package stats

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/rvagg/depsound/internal/gitdiff"
	"github.com/rvagg/depsound/internal/npmpkg"
)

func TestBuild(t *testing.T) {
	dir := t.TempDir()
	oldT, newT := filepath.Join(dir, "old"), filepath.Join(dir, "new")
	write := func(root, rel, content string) {
		t.Helper()
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write(oldT, "package.json", `{"name":"x","version":"1.0.0"}`)
	write(newT, "package.json", `{"name":"x","version":"2.0.0","scripts":{"postinstall":"node s.js"}}`)
	write(newT, "gen.pb.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\n")
	write(newT, "lib/a.js", "const a = 1;\n")
	// a vendored C header with no head marker but a deep version define:
	// must reclassify from source to generated and yield a marker delta
	write(oldT, "vendor.h", "/* copyright header */\nint f(void);\n#define LIBFOO_VERSION \"1.0.0\"\n")
	write(newT, "vendor.h", "/* copyright header */\nint f(void);\n#define LIBFOO_VERSION \"1.1.0\"\n")

	oldPkg, err := npmpkg.Load(oldT)
	if err != nil {
		t.Fatal(err)
	}
	newPkg, err := npmpkg.Load(newT)
	if err != nil {
		t.Fatal(err)
	}

	st, err := Build(Input{
		ToolVersion: "test",
		Pkg:         PkgRef{Ecosystem: "npm", Name: "x", From: "1.0.0", To: "2.0.0"},
		Workspace:   dir,
		OldTree:     oldT,
		NewTree:     newT,
		Diffs: []gitdiff.FileDiff{
			{Path: "package.json", Status: "M", Added: 1, Removed: 1},
			{Path: "gen.pb.go", Status: "A", Added: 1},
			{Path: "lib/a.js", Status: "A", Added: 1},
			{Path: "vendor.h", Status: "M", Added: 1, Removed: 1},
		},
		OldPkg:         oldPkg,
		NewPkg:         newPkg,
		SkippedLinks:   []string{"new: evil-link"},
		HostileEntries: []string{"new: \"../x\": escapes extraction root"},
		SourceFrom:     &Source{URL: "https://r/x-1.tgz", Digest: "sha512-a"},
		SourceTo:       &Source{URL: "https://r/x-2.tgz", Digest: "sha512-b"},
	})
	if err != nil {
		t.Fatal(err)
	}

	if st.Tool.Schema != SchemaVersion {
		t.Errorf("schema = %d", st.Tool.Schema)
	}
	if len(st.Runnable.Lifecycle) != 1 || st.Runnable.Lifecycle[0].Key != "postinstall" {
		t.Errorf("lifecycle = %+v", st.Runnable.Lifecycle)
	}
	if len(st.Artifact.SkippedLinks) != 1 || len(st.Artifact.HostileEntries) != 1 {
		t.Errorf("fidelity fields not plumbed: %+v", st.Artifact)
	}
	if st.Artifact.SourceFrom == nil || st.Artifact.SourceFrom.Digest != "sha512-a" {
		t.Errorf("provenance not plumbed: %+v", st.Artifact.SourceFrom)
	}
	byPath := map[string]FileEntry{}
	for _, e := range st.Files.Entries {
		byPath[e.Path] = e
	}
	if e := byPath["gen.pb.go"]; e.Class != "generated" || e.Evidence == "" {
		t.Errorf("gen.pb.go = %+v", e)
	}
	if e := byPath["package.json"]; e.Class != "meta" || e.Evidence == "" {
		t.Errorf("package.json = %+v", e)
	}
	if e := byPath["lib/a.js"]; e.Class != "source" || e.Evidence != "" {
		t.Errorf("lib/a.js = %+v", e)
	}
	if e := byPath["vendor.h"]; e.Class != "generated" || e.Evidence == "" {
		t.Errorf("vendored header not reclassified: %+v", e)
	}
	if len(st.Embedded) != 1 || st.Embedded[0].Name != "LIBFOO_VERSION" ||
		st.Embedded[0].From != "1.0.0" || st.Embedded[0].To != "1.1.0" {
		t.Errorf("embedded marker delta = %+v", st.Embedded)
	}
	// gen.pb.go (suffix) and vendor.h (marker vendored) are confidently
	// generated, so excluded from review surface with a disclaimer note;
	// package.json (meta) and lib/a.js (source) stay in.
	if st.Files.ReviewFiles != 2 {
		t.Errorf("review surface files = %d, want 2 (package.json + lib/a.js)", st.Files.ReviewFiles)
	}
	if len(st.Files.ExcludedGen) != 2 {
		t.Errorf("excluded generated = %v", st.Files.ExcludedGen)
	}
	if len(st.Notes) != 1 || !strings.Contains(st.Notes[0], "heuristic classified generated") {
		t.Errorf("expected the review-surface heuristic disclaimer, got: %v", st.Notes)
	}
}

func TestGHAPinNote(t *testing.T) {
	sha := "55cc8345863c7cc4c66a329aec7e433d2d1c52a9"
	src := func(kind string) *Source { return &Source{Digest: "git-" + sha, RefKind: kind} }

	// escalating tiers: sha immutable, tag mutable, branch unpinned
	if n := ghaPinNote("to", sha, src("sha")); strings.Contains(n, "WARNING") || !strings.Contains(n, "immutable") {
		t.Errorf("sha pin = %q", n)
	}
	if n := ghaPinNote("to", "v6.1.0", src("tag")); !strings.Contains(n, "WARNING") || !strings.Contains(n, "MUTABLE") || !strings.Contains(n, sha) {
		t.Errorf("tag pin = %q", n)
	}
	if n := ghaPinNote("to", "master", src("branch")); !strings.Contains(n, "WARNING") || !strings.Contains(n, "UNPINNED") {
		t.Errorf("branch pin = %q", n)
	}
	// fallback when the sidecar predates RefKind: infer from the ref shape
	if n := ghaPinNote("to", "v6.1.0", &Source{Digest: "git-" + sha}); !strings.Contains(n, "WARNING") {
		t.Errorf("fallback tag pin = %q", n)
	}
	if isHexSHA("v6.1.0") || !isHexSHA(sha) {
		t.Error("isHexSHA misclassified")
	}
}
