package stats

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/rvagg/depvet/internal/gitdiff"
	"github.com/rvagg/depvet/internal/npmpkg"
)

func TestBuild(t *testing.T) {
	dir := t.TempDir()
	oldT, newT := filepath.Join(dir, "old"), filepath.Join(dir, "new")
	write := func(root, rel, content string) {
		t.Helper()
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write(oldT, "package.json", `{"name":"x","version":"1.0.0"}`)
	write(newT, "package.json", `{"name":"x","version":"2.0.0","scripts":{"postinstall":"node s.js"}}`)
	write(newT, "gen.pb.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\n")
	write(newT, "lib/a.js", "const a = 1;\n")

	oldPkg, err := npmpkg.Load(oldT)
	if err != nil {
		t.Fatal(err)
	}
	newPkg, err := npmpkg.Load(newT)
	if err != nil {
		t.Fatal(err)
	}

	st, err := Build(Input{
		ToolVersion: "test",
		Pkg:         PkgRef{Ecosystem: "npm", Name: "x", From: "1.0.0", To: "2.0.0"},
		Workspace:   dir,
		OldTree:     oldT,
		NewTree:     newT,
		Diffs: []gitdiff.FileDiff{
			{Path: "package.json", Status: "M", Added: 1, Removed: 1},
			{Path: "gen.pb.go", Status: "A", Added: 1},
			{Path: "lib/a.js", Status: "A", Added: 1},
		},
		OldPkg:         oldPkg,
		NewPkg:         newPkg,
		SkippedLinks:   []string{"new: evil-link"},
		HostileEntries: []string{"new: \"../x\": escapes extraction root"},
		SourceFrom:     &Source{URL: "https://r/x-1.tgz", Digest: "sha512-a"},
		SourceTo:       &Source{URL: "https://r/x-2.tgz", Digest: "sha512-b"},
	})
	if err != nil {
		t.Fatal(err)
	}

	if st.Tool.Schema != SchemaVersion {
		t.Errorf("schema = %d", st.Tool.Schema)
	}
	if len(st.Runnable.Lifecycle) != 1 || st.Runnable.Lifecycle[0].Key != "postinstall" {
		t.Errorf("lifecycle = %+v", st.Runnable.Lifecycle)
	}
	if len(st.Artifact.SkippedLinks) != 1 || len(st.Artifact.HostileEntries) != 1 {
		t.Errorf("fidelity fields not plumbed: %+v", st.Artifact)
	}
	if st.Artifact.SourceFrom == nil || st.Artifact.SourceFrom.Digest != "sha512-a" {
		t.Errorf("provenance not plumbed: %+v", st.Artifact.SourceFrom)
	}
	byPath := map[string]FileEntry{}
	for _, e := range st.Files.Entries {
		byPath[e.Path] = e
	}
	if e := byPath["gen.pb.go"]; e.Class != "generated" || e.Evidence == "" {
		t.Errorf("gen.pb.go = %+v", e)
	}
	if e := byPath["package.json"]; e.Class != "meta" || e.Evidence == "" {
		t.Errorf("package.json = %+v", e)
	}
	if e := byPath["lib/a.js"]; e.Class != "source" || e.Evidence != "" {
		t.Errorf("lib/a.js = %+v", e)
	}
	if len(st.Notes) != 0 {
		t.Errorf("unexpected notes with full provenance: %v", st.Notes)
	}
}
